# Site settings
url: https://ebildungslabor.github.io
repo: eBildungslabor/simplewebsite
branch: github-master
title: Design Principles
description: An Open Source collection of Design Principles and methods
twitter: "@dsgnprinciples"
twitter:
  username: dsgnprinciples
logo: /favicon.png

twitter:
  image: https://principles.design/favicon.png
facebook:
  image: https://principles.design/favicon.png
# Custom
twitter-url: https://twitter.com/dsgnprinciples
contribute-url: https://github.com/benbrignell/principles.design#contributing
gitter-url: https://gitter.im/design-principles

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']

# Current site environment
environment: production

collections:
    examples:
        output: true
        permalink: /examples/:name
    components:
        output: false

defaults:
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "example"

exclude:
- node_modules
plugins:
- jekyll-seo-tag

liquid:
    error_mode: lax # because of featured loop on homepage throwing minor validation error
